### ISSUE TITLE
QUIC v1 (v1.21)

### ISSUE THREAD

**Issue by systemcrash** [ryoh/nginx-quic.spec#1]
Can this be bumped to v.1.21 (where, I think, RFC 9000 is implemented for QUIC v 1)?

Or is this strictly e.g. v1.19?

https://hg.nginx.org/nginx-quic/rev/8422570f6af4

**Comment by systemcrash** [comment]
Off topic, but such modules would also be 'cool' :)

https://github.com/tokers/zstd-nginx-module

( FB https://facebook.github.io/zstd/ references this )

**Comment by ryoh** [comment]
> Can this be bumped to v.1.21 (where, I think, RFC 9000 is implemented for QUIC v 1)?
> 
> Or is this strictly e.g. v1.19?
> 
> https://hg.nginx.org/nginx-quic/rev/8422570f6af4

Thanks. I not good at English.

Yes. But not doing soon. Please waiting.

**Comment by systemcrash** [comment]
いいよ。＾＾

**Comment by ryoh** [comment]
Thank.
Fix it.
